### ISSUE TITLE
AttributeError when trying to show available languages using show_available_languages

### ISSUE THREAD

**Issue by gaiar** [connor-makowski/srt-translator#11]
**Environment:**
- Python Version: 3.12
- Library Version: latest from pip install
- OS: MacOS 14.3.1

**Issue Description:**
When attempting to list the available languages supported by the `srt_file_translator` library using the `show_available_languages` method, I encountered an AttributeError.

**Steps to Reproduce:**
1. Initialize the Translator object with a specified `key_path`.
2. Call the `show_available_languages()` method on the Translator object.

**Expected Behavior:**
I expected the method to list all available languages supported by the `srt_file_translator`.

**Actual Behavior:**
Instead of listing the available languages, the following AttributeError is raised:
```
Traceback (most recent call last):
  File "/Users/gaiar/Developer/srt/check_langs.py", line 3, in <module>
    translator.show_available_languages()
AttributeError: 'Translator' object has no attribute 'show_available_languages'. Did you mean: '__available_languages__'?
```

**Code Snippet:**
```python
from srt_file_translator import Translator
translator = Translator(key_path="bq_key.json")
translator.show_available_languages()
```

**Possible Solution:**
It seems like the method name might be incorrect or not implemented as expected. If `__available_languages__` is the correct attribute or method for this purpose, the documentation might need an update, or perhaps there's an alternative method for listing languages.

**Comment by connor-makowski** [comment]
Thanks for reporting this issue. Let me look into it and post any updates here. I would expect a fix today. My apologies on the delay as github did not send me an issue notification.

Connor

**Comment by connor-makowski** [comment]
Just realized I never pushed and then closed this issue. It was a simple doc issue.

See: d4f82506b77541389951108f8cb714236d98f819
